version: '2'
services:
 zookeeper:
   image: wurstmeister/zookeeper:3.4.6
   container_name : zookeeper
   hostname : zookeeper
   networks:
      - tweets
   ports:
    - "2181:2181"
 kafka:
   image: wurstmeister/kafka
   container_name : kafka
   hostname: kafka
   ports:
   - "9092:9092"
   expose:
   - "9093"
   networks:
      - tweets
   environment:
    KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
    KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_CREATE_TOPICS: "topic_test:1:1"
   volumes:
   - /var/run/docker.sock:/var/run/docker.sock
 nifi:
   image: apache/nifi:latest
   container_name : nifi
   hostname : nifi
   networks:
      - tweets
   environment:
      - nifi.web.https.port=8443
      - nifi.web.http.port=8080
   ports:
      - 8080:8080
      - 8443:8443
 elasticsearch:
   build:
     context: elasticsearch/
   container_name : elasticsearch
   hostname : elasticsearch
   volumes:
     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
   networks:
     - tweets
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     ES_JAVA_OPTS: "-Xmx512m -Xms512m"
 kibana:
   build:
     context: kibana/
   container_name : kibana
   hostname : kibana
   volumes:
     - ./kibana/config/:/usr/share/kibana/config:ro
   ports:
     - "5601:5601"
   networks:
     - tweets
   depends_on:
     - elasticsearch

networks:
    tweets:
        driver: bridge
